development:
  adapter: postgresql
  encoding: unicode
  database: codetools_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: codetools_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: codetools_production
  pool: 5
